name: NuGet audit

on:
  workflow_call:
    outputs:
       restoreoutput:
         description: "Standard output of the dotnet restore call"
         value: ${{ jobs.nuget-audit.outputs.restoreoutput }}
    secrets:
      PROCESSNUGETAUDITRESULTS_KEY:
        required: true

jobs:
  nuget-audit:
    runs-on: ubuntu-22.04
    outputs:
      restoreoutput: ${{ steps.restore.outputs.restoreoutput }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4.1.0
        with:
          global-json-file: global.json
      - name: .NET Restore
        id: restore
        shell: bash        
        run: |
          mkdir ${{ github.workspace }}/results
          touch ${{ github.workspace }}/results/dotnetrestore.log
          set +e +o pipefail
          CVECOUNT=$(dotnet restore src | tee ${{ github.workspace }}/results/dotnetrestore.log | grep -c -e "NU190[1-4]")
          set -e -o pipefail
          exit_code=0
          RESTOREOUTPUT=$(cat ${{ github.workspace }}/results/dotnetrestore.log)
          echo $RESTOREOUTPUT
          #RESTOREOUTPUT="${RESTOREOUTPUT//'%'/'%25'}"
          #RESTOREOUTPUT="${RESTOREOUTPUT//$'\n'/'%0A'}"
          #RESTOREOUTPUT="${RESTOREOUTPUT//$'\r'/'%0D'}"
          echo "restoreoutput=$RESTOREOUTPUT" >> $GITHUB_OUTPUT
          
          exit $CVECOUNT
      - name: Upload results on failure
        if: ${{ failure() }}
        shell: bash
        working-directory: ./src
        run: |
          dotnet list package --vulnerable --include-transitive --format json >> "${{ github.workspace }}/results/vulnerabilities.json"
          jq -s '.' */obj/project.assets.json > "${{ github.workspace }}/results/all.project.assets.json"
          curl -X POST \
             -F "repository=${{ github.repository_id }}" \
             -F "branch=${{ github.ref_name }}" \
             -F "commit=${{ github.sha }}" \
             -F "vulnerabilities=${{ github.workspace }}/results/vulnerabilities.json" \
             -F "assets=${{ github.workspace }}/results/all.project.assets.json" \
             -H "x-functions-key: ${{ secrets.PROCESSNUGETAUDITRESULTS_KEY }}" \
             https://internalautomation.azurewebsites.net/api/ProcessNuGetAuditResults
      - name: Archive files on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: files
          path: ${{ github.workspace }}/results/
