name: NuGet audit

on:
  workflow_call:
    secrets:
      PROCESSNUGETAUDITRESULTS_KEY:
        required: true

jobs:
  nuget-audit:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4.1.0
        with:
          global-json-file: global.json
      - name: .NET Restore
        id: restore
        shell: bash        
        run: |
          dotnet restore src > ${{ runner.temp }}/dotnetrestore.log
          CVECOUNT=$(cat ${{ runner.temp }}/dotnetrestore.log | grep -c -e "NU190[1-4]")
          exit $CVECOUNT
      - name: Upload results on failure
        if: ${{ failure() }}
        shell: bash
        working-directory: ./src
        run: |
          mkdir ${{ github.workspace }}/results
          dotnet list package --vulnerable --include-transitive --format json >> "${{ github.workspace }}/results/vulnerabilities.json"
          jq -s '.' */obj/project.assets.json > "${{ github.workspace }}/results/all.project.assets.json"
          curl -X POST \
             -F "repository=${{ github.repository_id }}" \
             -F "branch=${{ github.ref_name }}" \
             -F "commit=${{ github.sha }}" \
             -F "vulnerabilities=${{ github.workspace }}/results/vulnerabilities.json" \
             -F "assets=${{ github.workspace }}/results/all.project.assets.json" \
             -H "x-functions-key: ${{ secrets.PROCESSNUGETAUDITRESULTS_KEY }}" \
             https://internalautomation.azurewebsites.net/api/ProcessNuGetAuditResults
      - name: Archive files on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: files
          path: |
            ${{ runner.temp }}/dotnetrestore.log
            ${{ github.workspace }}/results/*.json
