name: Code Analysis

on:
  workflow_call:
env:
  DOTNET_NOLOGO: true
defaults:
  run:
    shell: bash
jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4.1.0
        with:
          # Should match the version used in https://github.com/Particular/repo-integrity-action/blob/main/src/RepoIntegrityTests/RepoIntegrityTests.csproj
          dotnet-version: 8.0.x
      - name: Repo integrity tests
        id: run-tests
        uses: Particular/repo-integrity-action@main
      - name: Report warnings
        if: ${{  always() && steps.run-tests.outputs.has-warnings == 'true' }}
        run: cat code-analysis-warnings.md >> "$GITHUB_OUTPUT"
      - name: Upload warnings
        if: ${{ always() && steps.run-tests.outputs.has-warnings == 'true' }}
        uses: actions/upload-artifact@v4.6.0
        with:
          name: code-analysis-warnings
          path: code-analysis-warnings.md
          if-no-files-found: error
          retention-days: 30
